CREATE TABLE likes (
    id INT AUTO_INCREMENT COMMENT '序号',
    uid INT COMMENT '用户id',
    vid INT COMMENT '视频id',
    act INT COMMENT '是否点赞，1-点赞，0-没有点赞',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at DATETIME DEFAULT NULL COMMENT '删除时间',
    PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;